---
- name: Import awx_object variables
  block:
    - name: Create temp file for spec dict
      register: tmp_spec
      ansible.builtin.tempfile:
        state: file

    - name: Get AWX object definition from pvc
      kubernetes.core.k8s_cp:
        namespace: "{{ backup_pvc_namespace }}"
        pod: "{{ ansible_operator_meta.name }}-db-management"
        remote_path: "{{ backup_dir  }}/awx_object"
        local_path: "{{ tmp_spec.path }}"
        state: from_pod

    - name: Include spec vars to save them as a dict
      ansible.builtin.include_vars: "{{ tmp_spec.path }}"
