---
- name: Patching labels to {{ kind }} kind
  when: set_self_labels | bool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: "{{ api_version }}"
      kind: "{{ kind }}"
      name: "{{ ansible_operator_meta.name }}"
      namespace: "{{ ansible_operator_meta.namespace }}"
      metadata:
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        labels: '{{ lookup("template", "../common/templates/labels/common.yaml.j2") | from_yaml }}'

- name: Look up details for this backup object
  register: this_backup
  kubernetes.core.k8s_info:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"

- name: Build `additional_labels_items` labels from `additional_labels`
  when:
    - additional_labels | length
    - this_backup['resources'][0]['metadata']['labels']
  ansible.builtin.set_fact:
    additional_labels_items: >-
      {{ this_backup['resources'][0]['metadata']['labels']
         | dict2items | selectattr('key', 'in', additional_labels)
      }}

- block:
    - ansible.builtin.include_tasks: init.yml

    - ansible.builtin.include_tasks: postgres.yml

    - ansible.builtin.include_tasks: awx-cro.yml

    - ansible.builtin.include_tasks: secrets.yml

    - name: Set flag signifying this backup was successful
      ansible.builtin.set_fact:
        backup_complete: true

    - include_tasks: cleanup.yml

  when:
    - this_backup['resources'][0]['status']['backupDirectory'] is not defined

- name: Update status variables
  ansible.builtin.include_tasks: update_status.yml
