---
- name: Get secret name
  ansible.builtin.set_fact:
    _name: "{{ this_awx['resources'][0]['status'][item] }}"

- name: Fail if status is not set on AWX CR
  block:
    - name: Set error message
      ansible.builtin.set_fact:
        error_msg: "{{ item }} status is not set on AWX object yet"

    - name: Handle error
      ansible.builtin.import_tasks: error_handling.yml

    - name: Fail early if secret name status is not set
      fail:
        msg: "{{ error_msg }}"
  when: _name is not defined or _name == ''

- name: Get secret
  register: _secret
  no_log: "{{ no_log }}"
  kubernetes.core.k8s_info:
    version: v1
    kind: Secret
    namespace: "{{ ansible_operator_meta.namespace }}"
    name: "{{ _name }}"

- name: Set secret data
  no_log: "{{ no_log }}"
  ansible.builtin.set_fact:
    _data: "{{ _secret['resources'][0]['data'] }}"
    _type: "{{ _secret['resources'][0]['type'] }}"

- name: Create and Add secret names and data to dictionary
  no_log: "{{ no_log }}"
  ansible.builtin.set_fact:
    secret_dict: "{{ secret_dict | default({}) | combine({ item: {'name': _name, 'data': _data, 'type': _type }}) }}"
