---
- name: Dump (generated) secret names from statuses and data into file
  ansible.builtin.include_tasks: dump_generated_secret.yml
  loop:
    - secretKeySecret
    - adminPasswordSecret
    - broadcastWebsocketSecret
    - postgresConfigurationSecret

- name: Dump secret names from awx spec and data into file
  loop:
    - route_tls_secret
    - ingress_tls_secret
    - ldap_cacert_secret
    - bundle_cacert_secret
    - ee_pull_credentials_secret
  ansible.builtin.include_tasks: dump_secret.yml

- name: Dump ingress tls secret names from awx spec and data into file
  ansible.builtin.include_tasks: dump_ingress_tls_secrets.yml
  loop: "{{ awx_spec.spec['ingress_hosts'] | default([]) | selectattr('tls_secret', 'defined') | map(attribute='tls_secret') | list |flatten(levels=1) }}"

- name: Dump receptor secret names and data into file
  loop:
    - "{{ deployment_name }}-receptor-ca"
    - "{{ deployment_name }}-receptor-work-signing"
  ansible.builtin.include_tasks: dump_receptor_secrets.yml

- name: Dump image_pull_secret into file
  when: image_pull_secret is defined
  ansible.builtin.include_tasks: dump_secret.yml
  loop:
    - image_pull_secret

- name: Dump image_pull_secrets into file
  when: image_pull_secrets | default([]) | length
  ansible.builtin.include_tasks: dump_secret.yml
  loop:
    - image_pull_secrets

- name: Nest secrets under a single variable
  no_log: "{{ no_log }}"
  ansible.builtin.set_fact:
    secrets:
      secrets: "{{ secret_dict }}"

- name: Write postgres configuration to pvc
  no_log: "{{ no_log }}"
  kubernetes.core.k8s_cp:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-db-management"
    remote_path: "{{ backup_dir }}/secrets.yml"
    content: "{{ secrets | to_yaml }}"
