---
- name: Retrieve LDAP bind password Secret
  register: ldap_password
  no_log: "{{ no_log }}"
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ ansible_operator_meta.namespace }}"
    name: "{{ ldap_password_secret }}"

- name: Load LDAP bind password Secret content
  no_log: "{{ no_log }}"
  when: '"ldap-password" in ldap_password["resources"][0]["data"]'
  ansible.builtin.set_fact:
    ldap_bind_password: '{{ ldap_password["resources"][0]["data"]["ldap-password"] | b64decode }}'
