---
- name: Check for presence of old awx Deployment
  register: awx_deployment
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"

- name: Check for presence of awx-task Deployment
  register: awx_task_deployment
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ ansible_operator_meta.name }}-task"
    namespace: "{{ ansible_operator_meta.namespace }}"

- name: Check for presence of awx-web Deployment
  register: awx_web_deployment
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ ansible_operator_meta.name }}-web"
    namespace: "{{ ansible_operator_meta.namespace }}"

- name: Start installation if auto_upgrade is true
  when:
    - auto_upgrade | bool
  ansible.builtin.include_tasks: install.yml

- name: Start installation if auto_upgrade is false and deployment is missing
  when:
    - not (auto_upgrade | bool)
    - not (awx_deployment['resources'] | length > 0)
    - not (awx_web_deployment['resources'] | length > 0 and awx_task_deployment['resources'] | length > 0)
  ansible.builtin.include_tasks: install.yml
