---
- name: Check for pending migrations
  changed_when: false
  when: awx_web_pod_name != ''
  register: database_check
  kubernetes.core.k8s_exec:
    namespace: "{{ ansible_operator_meta.namespace }}"
    pod: "{{ awx_web_pod_name }}"
    container: "{{ ansible_operator_meta.name }}-web"
    command: >-
      bash -c "awx-manage showmigrations | grep -v '[X]' | grep '[ ]' | wc -l"

- block:
    - name: Get version of controller for tracking
      changed_when: false
      register: version_check
      kubernetes.core.k8s_exec:
        namespace: "{{ ansible_operator_meta.namespace }}"
        pod: "{{ awx_web_pod_name }}"
        container: "{{ ansible_operator_meta.name }}-web"
        command: >-
          bash -c "awx-manage --version"

    - name: Sanitize instance version
      ansible.builtin.set_fact:
        version: "{{ version_check.stdout.split('+')[0] | trim }}"

    # It is possible to do a wait on this task to create the job and wait
    # until it completes. Unfortunately, if the job doesn't wait finish within
    # the timeout period that is considered an error.  We only want this to
    # error if there is an issue with creating the job.

    - name: Create kubernetes job to perform the migration
      register: migrate_result

      # This task is really only necessary for new installations. We need to
      # ensure the database has a schema loaded before continuing with the
      # initialization of admin user, etc.
      kubernetes.core.k8s:
        apply: true
        definition: "{{ lookup('template', 'jobs/migration.yaml.j2') }}"

    - name: Watch for the migration job to finish
      k8s_info:
        kind: Job
        namespace: "{{ ansible_operator_meta.namespace }}"
        name: "{{ ansible_operator_meta.name }}-migration-{{ version }}"
      register: result
      until:
        - result.resources[0].status.succeeded is defined
        - result.resources[0].status.succeeded == 1
      retries: 180
      delay: 5
      ignore_errors: true

  when:
    - database_check is defined
    - (database_check.stdout|trim) != '0'
