---
- name: Get information about the cluster
  when:
    - not is_openshift | bool
    - not is_k8s | bool
  ansible.builtin.set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: Determine the cluster type
  when:
    - not is_openshift | bool
    - not is_k8s | bool
  ansible.builtin.set_fact:
    is_openshift: "{{ True if 'route.openshift.io' in api_groups else False }}"
    is_k8s: "{{ False if 'route.openshift.io' in api_groups else True }}"

- ansible.builtin.debug:
    msg: "CLUSTER TYPE: is_openshift={{ is_openshift }}; is_k8s={{ is_k8s }}"
